default_agent: csaiagent
agents:
  csaiagent:
    name: csaiagent
    language: python
    node_version: '20'
    entrypoint: /voc/work/Project_starter/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /voc/work/Project_starter
    aws:
      execution_role: arn:aws:iam::626694616296:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-129581ef7f
      execution_role_auto_create: false
      account: '626694616296'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-626694616296-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: csaiagent-BFKgR1FYgY
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:626694616296:runtime/csaiagent-BFKgR1FYgY
      agent_session_id: e5019d35-5a52-4623-a694-804a8976cab8
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: csaiagent_mem-jwiRHL7Brs
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:626694616296:memory/csaiagent_mem-jwiRHL7Brs
      memory_name: csaiagent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
